// backend/modules/exam/exam.service.js
import prisma from "../../utils/prisma.js";

const nf = (msg="Exam not found") => Object.assign(new Error(msg), { status:404 });

// ── EXAM CRUD ─────────────────────────────────────────────────
export const listExams = async ({ session_id, exam_type, status, dept_id, page=1, limit=20 }) => {
  const where = { deleted_at: null };
  if (session_id)  where.session_id = session_id;
  if (exam_type)   where.exam_type  = exam_type;
  if (status)      where.status     = status;
  if (dept_id)     where.dept_ids   = { has: dept_id };
  const skip = (page-1)*limit;
  const [items, total] = await Promise.all([
    prisma.exam.findMany({ where, skip, take:+limit, include:{ _count:{ select:{ schedule:true, seatings:true, hallTickets:true } } }, orderBy:{ start_date:"asc" } }),
    prisma.exam.count({ where }),
  ]);
  return { items, total, page:+page, limit:+limit };
};

export const getExam = async (id) => {
  const e = await prisma.exam.findUnique({ where:{ id }, include:{ schedule:{ include:{ subject:true } }, rooms:{ include:{ room:true } }, hallTickets:{ select:{ id:true, student_id:true } } } });
  if (!e) throw nf();
  return e;
};

export const createExam = async (data, created_by) =>
  prisma.exam.create({ data:{ ...data, created_by, status:"DRAFT" } });

export const updateExam = async (id, data) => {
  const e = await prisma.exam.findUnique({ where:{ id } });
  if (!e) throw nf();
  return prisma.exam.update({ where:{ id }, data });
};

export const cancelExam = async (id, reason, cancelled_by) =>
  prisma.exam.update({ where:{ id }, data:{ status:"CANCELLED", cancel_reason:reason, cancelled_by, cancelled_at:new Date() } });

// ── SCHEDULE ──────────────────────────────────────────────────
export const addScheduleEntry = async (exam_id, data) =>
  prisma.examSchedule.create({ data:{ ...data, exam_id } });

export const updateScheduleEntry = async (id, data) =>
  prisma.examSchedule.update({ where:{ id }, data });

export const deleteScheduleEntry = async (id) =>
  prisma.examSchedule.delete({ where:{ id } });

// Auto-generate datesheet from academic calendar
export const autoGenerateDatesheet = async (exam_id, { start_date, subjects_per_day=1, skip_holidays=true, session_id }) => {
  const exam     = await prisma.exam.findUnique({ where:{ id:exam_id }, include:{ schedule:{ include:{ subject:true } } } });
  if (!exam) throw nf();
  
  const holidays = skip_holidays ? await prisma.academicCalendarEvent.findMany({
    where: { session_id: session_id||exam.session_id, is_holiday:true, deleted_at:null },
    select: { start_date:true, end_date:true },
  }) : [];

  const isHoliday = (date) => holidays.some(h => date >= h.start_date && date <= h.end_date);

  let current = new Date(start_date);
  const entries = [];

  for (const sch of exam.schedule) {
    while (isHoliday(current) || current.getDay() === 0) {
      current.setDate(current.getDate() + 1);
    }
    entries.push({ ...sch, suggested_date: new Date(current) });
    current.setDate(current.getDate() + 1);
  }

  return entries;
};

// ── SEATING ───────────────────────────────────────────────────
export const autoGenerateSeating = async (exam_id, exam_date) => {
  // Get all students for this exam (from sections/branches in schedule)
  const exam = await prisma.exam.findUnique({ where:{ id:exam_id }, include:{ schedule:true, rooms:{ where:{ exam_date: new Date(exam_date) }, include:{ room:true } } } });
  if (!exam) throw nf();

  const section_ids = [...new Set(exam.schedule.flatMap(s => s.section_ids))];
  const students    = await prisma.student.findMany({
    where: { section_id:{ in:section_ids }, status:"ACTIVE" },
    select: { id:true, roll_no:true, name:true },
    orderBy: { roll_no:"asc" },
  });

  // Shuffle branches (mix different sections)
  const shuffled = students.sort(() => Math.random() - 0.5);

  const rooms   = exam.rooms;
  let roomIdx   = 0, seatNo = 1;
  const seatings = [];

  for (const student of shuffled) {
    if (roomIdx >= rooms.length) break;
    const room = rooms[roomIdx];
    
    seatings.push({
      exam_id, exam_room_id: room.id, student_id: student.id,
      roll_no: student.roll_no, seat_no: `${String.fromCharCode(65+roomIdx)}${seatNo}`,
      exam_date: new Date(exam_date),
    });

    seatNo++;
    if (seatNo > room.capacity) { roomIdx++; seatNo = 1; }
  }

  // Delete existing auto seatings
  await prisma.examSeating.deleteMany({ where: { exam_id, exam_date:new Date(exam_date), is_manual:false } });

  // Create new
  await prisma.examSeating.createMany({ data: seatings, skipDuplicates:true });
  return { generated: seatings.length, rooms: rooms.length };
};

export const overrideSeating = async (seating_id, data) =>
  prisma.examSeating.update({ where:{ id:seating_id }, data:{ ...data, is_manual:true } });

// ── HALL TICKETS ──────────────────────────────────────────────
export const generateHallTickets = async (exam_id, student_ids = []) => {
  if (!student_ids.length) {
    const seatings = await prisma.examSeating.findMany({ where:{ exam_id }, select:{ student_id:true } });
    student_ids = [...new Set(seatings.map(s => s.student_id))];
  }

  const results = [];
  for (const student_id of student_ids) {
    const ticket_no = `HT-${exam_id.slice(-4).toUpperCase()}-${student_id.slice(-6).toUpperCase()}`;
    const r = await prisma.hallTicket.upsert({
      where:  { exam_id_student_id:{ exam_id, student_id } },
      update: { ticket_no, is_valid:true, generated_at:new Date() },
      create: { exam_id, student_id, ticket_no, is_valid:true },
    });
    results.push(r);
  }
  return { generated: results.length };
};

export const getHallTicketData = async (exam_id, student_id) => {
  const [student, exam, seatings, ticket] = await Promise.all([
    prisma.student.findUnique({ where:{ id:student_id }, include:{ branch:true, section:true } }),
    prisma.exam.findUnique({ where:{ id:exam_id }, include:{ schedule:{ include:{ subject:true } } } }),
    prisma.examSeating.findMany({ where:{ exam_id, student_id }, include:{ exam_room:{ include:{ room:true } } } }),
    prisma.hallTicket.findUnique({ where:{ exam_id_student_id:{ exam_id, student_id } } }),
  ]);
  return { student, exam, seatings, ticket };
};

// ── MARKS ─────────────────────────────────────────────────────
export const enterMarks = async (exam_id, subject_id, marks_data, entered_by) => {
  const results = [];
  for (const m of marks_data) {
    const r = await prisma.examMark.upsert({
      where:  { exam_id_student_id_subject_id:{ exam_id, student_id:m.student_id, subject_id } },
      update: { marks_obtained:m.marks, is_absent:m.is_absent||false, remarks:m.remarks, entered_by },
      create: { exam_id, student_id:m.student_id, subject_id, exam_type:m.exam_type, marks_obtained:m.marks||0, max_marks:m.max_marks||100, is_absent:m.is_absent||false, remarks:m.remarks, entered_by },
    });
    results.push(r);
  }
  return results;
};

export const publishResults = async (exam_id) => {
  await prisma.examMark.updateMany({ where:{ exam_id }, data:{ result_published:true } });
  return prisma.exam.update({ where:{ id:exam_id }, data:{ result_published:true, result_published_at:new Date() } });
};

export const getReport = async (exam_id) => {
  const [exam, marks] = await Promise.all([
    prisma.exam.findUnique({ where:{ id:exam_id }, include:{ schedule:{ include:{ subject:true } } } }),
    prisma.examMark.findMany({ where:{ exam_id }, include:{ student:{ select:{ id:true, name:true, roll_no:true, section:{ select:{ name:true } } } }, subject:{ select:{ id:true, name:true, code:true } } } }),
  ]);
  const bySubject = {};
  for (const m of marks) {
    const key = m.subject_id;
    if (!bySubject[key]) bySubject[key] = { subject:m.subject, entries:[], total:0, pass:0, absent:0, avg:0 };
    bySubject[key].entries.push(m);
    if (m.is_absent) bySubject[key].absent++;
    else {
      bySubject[key].total++;
      const pct = m.max_marks > 0 ? m.marks_obtained/m.max_marks*100 : 0;
      if (pct >= 40) bySubject[key].pass++;
    }
  }
  for (const k of Object.keys(bySubject)) {
    const s = bySubject[k];
    const present = s.entries.filter(e => !e.is_absent);
    s.avg = present.length ? +(present.reduce((sum,e) => sum+e.marks_obtained, 0)/present.length).toFixed(1) : 0;
    s.pass_pct = s.total > 0 ? +(s.pass/s.total*100).toFixed(1) : 0;
  }
  return { exam, subjectReport: Object.values(bySubject), total_marks: marks.length, total_absent: marks.filter(m=>m.is_absent).length };
};
