import { Router } from "express";
import { authenticate, requirePerm } from "../../middlewares/auth.middleware.js";
import * as svc from "./exam.service.js";

const router = Router();
const ok   = (res, d, msg="OK", s=200) => res.status(s).json({ success:true, message:msg, data:d });
const fail = (res, e, next) => e.status ? res.status(e.status).json({ success:false, message:e.message }) : next(e);
router.use(authenticate);

// Exam CRUD
router.get(   "/",                         requirePerm("exam:view"),     async (r,s,n)=>{ try{ok(s,await svc.listExams(r.query));}catch(e){fail(s,e,n);} });
router.post(  "/",                         requirePerm("exam:create"),   async (r,s,n)=>{ try{ok(s,await svc.createExam(r.body,r.user.id),"Created",201);}catch(e){fail(s,e,n);} });
router.get(   "/:id",                      requirePerm("exam:view"),     async (r,s,n)=>{ try{ok(s,await svc.getExam(r.params.id));}catch(e){fail(s,e,n);} });
router.patch( "/:id",                      requirePerm("exam:edit"),     async (r,s,n)=>{ try{ok(s,await svc.updateExam(r.params.id,r.body));}catch(e){fail(s,e,n);} });
router.post(  "/:id/cancel",               requirePerm("exam:edit"),     async (r,s,n)=>{ try{ok(s,await svc.cancelExam(r.params.id,r.body.reason,r.user.id));}catch(e){fail(s,e,n);} });
// Schedule
router.post(  "/:id/schedule",             requirePerm("exam:edit"),     async (r,s,n)=>{ try{ok(s,await svc.addScheduleEntry(r.params.id,r.body),"Added",201);}catch(e){fail(s,e,n);} });
router.patch( "/schedule/:sid",            requirePerm("exam:edit"),     async (r,s,n)=>{ try{ok(s,await svc.updateScheduleEntry(r.params.sid,r.body));}catch(e){fail(s,e,n);} });
router.delete("/schedule/:sid",            requirePerm("exam:edit"),     async (r,s,n)=>{ try{ok(s,await svc.deleteScheduleEntry(r.params.sid));}catch(e){fail(s,e,n);} });
router.post(  "/:id/auto-datesheet",       requirePerm("exam:edit"),     async (r,s,n)=>{ try{ok(s,await svc.autoGenerateDatesheet(r.params.id,r.body));}catch(e){fail(s,e,n);} });
// Seating
router.post(  "/:id/seating/generate",     requirePerm("exam:seating"),  async (r,s,n)=>{ try{ok(s,await svc.autoGenerateSeating(r.params.id,r.body.exam_date));}catch(e){fail(s,e,n);} });
router.patch( "/seating/:sid",             requirePerm("exam:seating"),  async (r,s,n)=>{ try{ok(s,await svc.overrideSeating(r.params.sid,r.body));}catch(e){fail(s,e,n);} });
// Hall tickets
router.post(  "/:id/hall-tickets/generate",requirePerm("exam:tickets"),  async (r,s,n)=>{ try{ok(s,await svc.generateHallTickets(r.params.id,r.body.student_ids));}catch(e){fail(s,e,n);} });
router.get(   "/:id/hall-tickets/:sid",    requirePerm("exam:view"),     async (r,s,n)=>{ try{ok(s,await svc.getHallTicketData(r.params.id,r.params.sid));}catch(e){fail(s,e,n);} });
// Marks
router.post(  "/:id/marks/:subject_id",    requirePerm("exam:marks"),    async (r,s,n)=>{ try{ok(s,await svc.enterMarks(r.params.id,r.params.subject_id,r.body.marks,r.user.id));}catch(e){fail(s,e,n);} });
router.post(  "/:id/publish-results",      requirePerm("exam:publish"),  async (r,s,n)=>{ try{ok(s,await svc.publishResults(r.params.id));}catch(e){fail(s,e,n);} });
router.get(   "/:id/report",               requirePerm("exam:view"),     async (r,s,n)=>{ try{ok(s,await svc.getReport(r.params.id));}catch(e){fail(s,e,n);} });
export default router;
